LOAD DATA
APPEND INTO TABLE DATOSDECAMPO.AGD_MUESTRAS_VARIABLES
WHEN (ID_MUESTRA != '0' )
FIELDS TERMINATED BY x'09' 
-- Separdos por tab las columnas vacias vienen como dos tabs seguidos OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
ID_PARAMETRO INTEGER EXTERNAL,
ID_METODOLOGIA INTEGER EXTERNAL,
ID_UNIDAD_MEDIDA INTEGER EXTERNAL,
ID_MUESTRA INTEGER EXTERNAL,
ID_METODO INTEGER EXTERNAL,
VALOR CHAR,

